# Consulte https://aka.ms/customizecontainer para aprender a personalizar su contenedor de depuración y cómo Visual Studio usa este Dockerfile para compilar sus imágenes para una depuración más rápida.

# Esta fase se usa cuando se ejecuta desde VS en modo rápido (valor predeterminado para la configuración de depuración)
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER root
RUN apt-get update \
    && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*
USER $APP_UID
WORKDIR /app
EXPOSE 8080
EXPOSE 8081


# Esta fase se usa para compilar el proyecto de servicio
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY ["MiKompri.ShoppingList.Api/MiKompri.ShoppingList.Api.csproj", "MiKompri.ShoppingList.Api/"]
COPY ["MiKompri.ShoppingList.Application/MiKompri.ShoppingList.Application.csproj", "MiKompri.ShoppingList.Application/"]
COPY ["MiKompri.ShoppingList.Domain/MiKompri.ShoppingList.Domain.csproj", "MiKompri.ShoppingList.Domain/"]
COPY ["MiKompri.ShoppingList.Infrastructure/MiKompri.ShoppingList.Infrastructure.csproj", "MiKompri.ShoppingList.Infrastructure/"]
RUN dotnet restore "./MiKompri.ShoppingList.Api/MiKompri.ShoppingList.Api.csproj"
COPY . .
WORKDIR "/src/MiKompri.ShoppingList.Api"
RUN dotnet build "./MiKompri.ShoppingList.Api.csproj" -c $BUILD_CONFIGURATION -o /app/build

# Esta fase se usa para publicar el proyecto de servicio que se copiará en la fase final.
FROM build AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish "./MiKompri.ShoppingList.Api.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

# Esta fase se usa en producción o cuando se ejecuta desde VS en modo normal (valor predeterminado cuando no se usa la configuración de depuración)
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "MiKompri.ShoppingList.Api.dll"]