// <auto-generated />
using System;
using MiKompri.ShoppingList.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MiKompri.ShoppingList.Infrastructure.Migrations
{
    [DbContext(typeof(ShoppingListDbContext))]
    [Migration("20260812104441_SyncPendingChanges")]
    partial class SyncPendingChanges
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MiKompri.ShoppingList.Domain.Entities.ExpenseParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemExpenseRecordId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantUserId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ShareAmount")
                        .HasColumnType("decimal(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ItemExpenseRecordId", "ParticipantUserId")
                        .IsUnique();

                    b.ToTable("shared_list_expense_participants", (string)null);
                });

            modelBuilder.Entity("MiKompri.ShoppingList.Domain.Entities.ItemExpenseRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)");

                    b.Property<DateTime>("ExpenseDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("PaidBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("PurchasedBy")
                        .HasColumnType("uuid");

                    b.Property<decimal>("RealPaidPrice")
                        .HasColumnType("decimal(12,2)");

                    b.Property<Guid>("SharedListItemId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SharedListItemId");

                    b.ToTable("shared_list_item_expenses", (string)null);
                });

            modelBuilder.Entity("MiKompri.ShoppingList.Domain.Entities.ListItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AddedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsPurchased")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PurchaseListId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PurchaseListId", "ProductId")
                        .IsUnique();

                    b.ToTable("list_items", (string)null);
                });

            modelBuilder.Entity("MiKompri.ShoppingList.Domain.Entities.PurchaseList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid?>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("OwnerId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("purchase_lists", (string)null);
                });

            modelBuilder.Entity("MiKompri.ShoppingList.Domain.Entities.SharedListAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Metadata")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("SharedPurchaseListId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetEntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetEntityType")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.HasKey("Id");

                    b.HasIndex("SharedPurchaseListId");

                    b.ToTable("shared_list_audit_events", (string)null);
                });

            modelBuilder.Entity("MiKompri.ShoppingList.Domain.Entities.ExpenseParticipant", b =>
                {
                    b.HasOne("MiKompri.ShoppingList.Domain.Entities.ItemExpenseRecord", null)
                        .WithMany("Participants")
                        .HasForeignKey("ItemExpenseRecordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiKompri.ShoppingList.Domain.Entities.ItemExpenseRecord", b =>
                {
                    b.HasOne("MiKompri.ShoppingList.Domain.Entities.ListItem", null)
                        .WithMany("Expenses")
                        .HasForeignKey("SharedListItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MiKompri.ShoppingList.Domain.Entities.ListItem", b =>
                {
                    b.HasOne("MiKompri.ShoppingList.Domain.Entities.PurchaseList", "PurchaseList")
                        .WithMany("Items")
                        .HasForeignKey("PurchaseListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PurchaseList");
                });

            modelBuilder.Entity("MiKompri.ShoppingList.Domain.Entities.ItemExpenseRecord", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("MiKompri.ShoppingList.Domain.Entities.ListItem", b =>
                {
                    b.Navigation("Expenses");
                });

            modelBuilder.Entity("MiKompri.ShoppingList.Domain.Entities.PurchaseList", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
