name: CD - MiKompri ShoppingList API

on:
  push:
    tags:
      - 'v*.*.*'   # v0.1.0, v1.0.0, etc.

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # necesario para publicar en GHCR

    env:
      IMAGE_NAME: ghcr.io/${{ github.repository_owner }}/mikompri-shoppinglist-api

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build \
            -f MiKompri.ShoppingList.Api/Dockerfile \
            -t $IMAGE_NAME:${{ github.ref_name }} \
            -t $IMAGE_NAME:latest \
            --build-arg BUILD_CONFIGURATION=Release \
            .

      - name: Push Docker image
        run: |
          docker push $IMAGE_NAME:${{ github.ref_name }}
          docker push $IMAGE_NAME:latest
